name: chatview
description: A Flutter package that allows you to integrate Chat View with
  highly customization options.
version: 2.1.0
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  ? android
  ? ios

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  any_link_preview: ^3.0.1
  audio_waveforms: ^1.0.5
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  emoji_picker_flutter: ^2.1.1
  flutter:
    sdk: flutter
  image_picker: ">=0.8.9 <2.0.0"
  intl: ^0.19.0
  path_provider: ^2.1.3
  timeago: ^3.6.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
